name: Executables

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macOS-latest"]
        architecture: ["x64"]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Date
      run: echo "DATE=$(date '+%Y%m%d')" >> "$GITHUB_ENV"

    - name: Update Version
      run: |
        sed --regexp-extended --in-place \
            's/(__version__ = "[0-9]+\.[0-9]+\.[0-9]+)(-dev)?/\1.${{ env.DATE }}/' \
            ./application/version.py
        cat ./application/version.py

    - name: Build executable
      env:
        MATRIX_OS: ${{ matrix.os }}
        MATRIX_ARCH: ${{ matrix.architecture }}
      run: |
        pip install pyinstaller
        python ./pyinstaller.py

    - uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
        path: dist/*
        retention-days: 1
        compression-level: 0

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Date
      run: echo "DATE=$(date '+%Y%m%d')" >> "$GITHUB_ENV"

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4

    - name: debug 123
      run: |
        echo
        echo After Download
        find .
        echo

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "executable-*/*"
        owner: steven23851-org
        repo: builds
        tag: ${{ env.DATE }}
