name: Executables

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

env:
  DATE_FORMAT: "%Y.%m.%d"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macOS-latest"]
        architecture: ["x64"]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Date
      run: echo "DATE=$(date '+${{ env.DATE_FORMAT }}')" >> "$GITHUB_ENV"

    - name: Update Version
      shell: python
      run: |
        import re
        path = "./application/version.py"
        with open(path) as fp:
            content = fp.read()
        content = re.sub(
            r'\b(__version__ = "[^"]+)',
            r"\1:${{ env.DATE }}",
            content)
        with open(path, "w") as fp:
            fp.write(content)

    - name: Build executable
      run: |
        pip install pyinstaller
        python ./pyinstaller.py -o '${{ matrix.os }}' -a '${{ matrix.architecture }}'

    - uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
        path: dist/*
        retention-days: 1
        compression-level: 0

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Date
      run: echo "DATE=$(date '+${{ env.DATE_FORMAT }}')" >> "$GITHUB_ENV"

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4

    - name: debug 123
      run: |
        echo
        echo After Download
        find .
        echo

    - uses: ncipollo/release-action@v1
      with:
        owner: steven23851-org
        repo: builds
        tag: ${{ env.DATE }}
        artifacts: "executable-*/*"
        allowUpdates: true
        makeLatest: true
        token: ${{ secrets.RELEASE_TOKEN }}
