name: Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/metadata-action@v5
      id: metadata
      with:
        images: |
          steven23851/test
          ghcr.io/steven23851/test
        flavor: |
          latest=true
          prefix=PRE
          suffix=SUF
        tags: |
          type=ref,event=tag
          type=sha,format=long
          type=raw,value={{date 'YYYYMMDD'}}

    - run: |
        echo TAGS:
        echo "${{ steps.metadata.outputs.tags }}"
        echo
        echo LABELS:
        echo "${{ steps.metadata.outputs.labels }}"
