name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  dispatch:
    if: github.repository == 'steven23851/test'
    runs-on: ubuntu-latest
    steps:
    - name: dispatch
      run: >
        curl -L
        -X POST
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/steven23851-org/docs/actions/workflows/pages.yml/dispatches
        -d '{"ref":"master"}'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4

      - name: Copy static files
        run: |
          mkdir ./_site
          cp -a -t ./_site ./docs/static.html

      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
        id: deployment
